In [92]:
import pandas as pd

melbourne_file_path = "D:\Data is the new Oil\MachineLearning_Python\Data\melb_data.csv\melb_data.csv"
melb_data = pd.read_csv(melbourne_file_path) 
melb_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [10]:
melb_data.shape

(13580, 21)

In [18]:
#Dropping NAs
melb_data  = melb_data.dropna(axis= 0)
melb_data.shape

(6196, 21)

### Chosing the Prediction Target

We'll use the dot notation to select the column we want to predict, which is called the prediction target. By convention, the prediction target is called y. So the code we need to save the house prices in the Melbourne data is

In [20]:
y= melb_data.Price
y

1        1035000.0
2        1465000.0
4        1600000.0
6        1876000.0
7        1636000.0
           ...    
12205     601000.0
12206    1050000.0
12207     385000.0
12209     560000.0
12212    2450000.0
Name: Price, Length: 6196, dtype: float64

In [21]:
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6196 entries, 1 to 12212
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Suburb         6196 non-null   object 
 1   Address        6196 non-null   object 
 2   Rooms          6196 non-null   int64  
 3   Type           6196 non-null   object 
 4   Price          6196 non-null   float64
 5   Method         6196 non-null   object 
 6   SellerG        6196 non-null   object 
 7   Date           6196 non-null   object 
 8   Distance       6196 non-null   float64
 9   Postcode       6196 non-null   float64
 10  Bedroom2       6196 non-null   float64
 11  Bathroom       6196 non-null   float64
 12  Car            6196 non-null   float64
 13  Landsize       6196 non-null   float64
 14  BuildingArea   6196 non-null   float64
 15  YearBuilt      6196 non-null   float64
 16  CouncilArea    6196 non-null   object 
 17  Lattitude      6196 non-null   float64
 18  Longtit

### Choosing Features
The columns that are inputted into our model (and later used to make predictions) are called "features." In our case, those would be the columns used to determine the home price.

Will use a model with few features


In [28]:

melb_features = ["Rooms", "Bathroom", "Landsize", "Lattitude","Longtitude"]
melb_features

['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

In [30]:
x = melb_data[melb_features]
x

Rooms  Bathroom  Landsize  Lattitude  Longtitude
1          2       1.0     156.0  -37.80790   144.99340
2          3       2.0     134.0  -37.80930   144.99440
4          4       1.0     120.0  -37.80720   144.99410
6          3       2.0     245.0  -37.80240   144.99930
7          2       1.0     256.0  -37.80600   144.99540
...      ...       ...       ...        ...         ...
12205      3       2.0     972.0  -37.51232   145.13282
12206      3       1.0     179.0  -37.86558   144.90474
12207      1       1.0       0.0  -37.85588   144.89936
12209      2       1.0       0.0  -37.85581   144.99025
12212      6       3.0    1087.0  -37.81038   144.89389

[6196 rows x 5 columns]

In [32]:
x.head()

Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954

### Building the Model
We will use scikit-learn package and decision tree algorithm

In [38]:
from sklearn.tree import DecisionTreeRegressor

# Define model. Specify a number for random_state to ensure same results each run
melb_model = DecisionTreeRegressor(random_state=2)

# Fit model
melb_model.fit(x, y)

DecisionTreeRegressor(random_state=2)

In [36]:
# Using it for predictions
print("Making predictions for the following 5 houses:")
print(x.head())
print("The predictions are")
print(melb_model.predict(x.head()))

Making predictions for the following 5 houses:
   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954
The predictions are
[1035000. 1465000. 1600000. 1876000. 1636000.]


In [40]:
# Using it for predictions
print("Making predictions for the following 5 houses:")
print(x.head())
print("The predictions are")
print(melb_model.predict(x.head()))

Making predictions for the following 5 houses:
   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954
The predictions are
[1035000. 1465000. 1600000. 1876000. 1636000.]


### Decision Tree for Classification
In this section we will predict whether a bank note is authentic or fake depending 
upon the four different attributes of the image of the note. 
The attributes are Variance of wavelet transformed image,
curtosis of the image, entropy, and skewness of the image.

In [49]:
#Libraries and importing datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
 
bank_note = pd.read_csv(r"D:\Data is the new Oil\MachineLearning_Python\Data\bill_authentication\bill_authentication.csv")

In [50]:
bank_note.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Variance  1372 non-null   float64
 1   Skewness  1372 non-null   float64
 2   Curtosis  1372 non-null   float64
 3   Entropy   1372 non-null   float64
 4   Class     1372 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 53.7 KB


In [51]:
bank_note.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

### Preaparing The Data
In this section we will divide our data into attributes and labels and will then divide the
resultant data into both training and test sets. By doing this we can train our algorithm
on one set of data and then test it out on a completely different set of data that the
algorithm hasn't seen yet. This provides you with a more accurate view of how your trained
algorithm will actually perform

In [59]:
x = bank_note.drop('Class', axis=1) # drops the column class from the dataset
y = bank_note['Class']              # gets the column class in the dataset


Variance  Skewness  Curtosis  Entropy
0      3.62160   8.66610   -2.8073 -0.44699
1      4.54590   8.16740   -2.4586 -1.46210
2      3.86600  -2.63830    1.9242  0.10645
3      3.45660   9.52280   -4.0112 -3.59440
4      0.32924  -4.45520    4.5718 -0.98880
...        ...       ...       ...      ...
1367   0.40614   1.34920   -1.4501 -0.55949
1368  -1.38870  -4.87730    6.4774  0.34179
1369  -3.75030 -13.45860   17.5932 -2.77710
1370  -3.56370  -8.38270   12.3930 -1.28230
1371  -2.54190  -0.65804    2.6842  1.19520

[1372 rows x 4 columns]

### Slitting the Data
The final preprocessing step is to divide our data into training and test sets.
The model_selection library of Scikit-Learn contains train_test_split method, 
which we'll use to randomly split the data into training andtesting sets

In [63]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)
x_train.shape

(1097, 4)

In [65]:
x_test.shape

(275, 4)

### Training and Making Predictions
Once the data has been divided into the training and testing sets, the final step is to train 
the decision tree algorithm on this data and make predictions. Scikit-Learn contains the tree
library, which contains built-in classes/methods for various decision tree algorithms. 
Since we are going to perform a classification task here, we will use the 
DecisionTreeClassifier class for this example. The fit method of this class is called to train
the algorithm on the training data, which is passed as parameter to the fit method.

In [66]:

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)

DecisionTreeClassifier()

In [67]:
# Making predisctions
y_pred = classifier.predict(x_test)

### Evaluating the Algorithm
At this point we have trained our algorithm and made some predictions. Now we'll see how
accurate our algorithm is. For classification tasks some commonly used metrics are confusion
matrix, precision, recall, and F1 score. Lucky for us Scikit=-Learn's metrics library contains
the classification_report and confusion_matrix methods that can be used to calculate these
metrics for us:

In [68]:
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
df

Actual  Predicted
963        1          1
236        0          0
423        0          0
1327       1          1
716        0          0
...      ...        ...
93         0          0
861        1          1
863        1          1
1246       1          1
1181       1          1

[275 rows x 2 columns]

In [69]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

[[144   3]
 [  1 127]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       147
           1       0.98      0.99      0.98       128

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



In [ ]:
From the confusion matrix, you can see that out of 275 test instances, our algorithm
misclassified only 4. This is 98.5 % accuracy. Not too bad!

## Decision tree for Regression 
The process of solving regression problem with decision tree using Scikit Learn is very 
similar to that of classification. However for regression we use DecisionTreeRegressor
class of the tree library. Also the evaluation matrics for regression differ from those of 
classification. The rest of the process is almost same.

In [71]:
fuel_cons = pd.read_csv("D:\Data is the new Oil\MachineLearning_Python\Data\Petrol_Consumption\Petrol_Consumption.csv")
fuel_cons.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [72]:
fuel_cons.describe()

Petrol_tax  Average_income  Paved_Highways  \
count   48.000000       48.000000       48.000000   
mean     7.668333     4241.833333     5565.416667   
std      0.950770      573.623768     3491.507166   
min      5.000000     3063.000000      431.000000   
25%      7.000000     3739.000000     3110.250000   
50%      7.500000     4298.000000     4735.500000   
75%      8.125000     4578.750000     7156.000000   
max     10.000000     5342.000000    17782.000000   

       Population_Driver_licence(%)  Petrol_Consumption  
count                     48.000000           48.000000  
mean                       0.570333          576.770833  
std                        0.055470          111.885816  
min                        0.451000          344.000000  
25%                        0.529750          509.500000  
50%                        0.564500          568.500000  
75%                        0.595250          632.750000  
max                        0.724000          968.000000

In [88]:
# Data Consumption
x = fuel_cons.drop('Petrol_Consumption', axis=1)
y = fuel_cons['Petrol_Consumption']
# Data Splitting
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
y.shape


(48,)

In [78]:
#Data training 
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(x_train, y_train)

DecisionTreeRegressor()

In [91]:
y_test.shape

(10,)

In [83]:
#prediction
y_pred = regressor.predict(x_test)
y_pred

array([547., 414., 574., 554., 631., 644., 648., 524., 414., 464.])

In [93]:

#Comparing
df = pd.DataFrame({"Actual":y_test, "Predicted":y_pred})
df

Actual  Predicted
29     534      547.0
4      410      414.0
26     577      574.0
30     571      554.0
32     577      631.0
37     704      644.0
34     487      648.0
40     587      524.0
7      467      414.0
10     580      464.0

In [94]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 54.4
Mean Squared Error: 5315.4
Root Mean Squared Error: 72.90678980726007


In [ ]:
The mean absolute error for our algorithm is 54.4, which is less than 10 percent of the mean
of all the values in the 'Petrol_Consumption' column. This means that our algorithm did a good prediction.